[2024-07-06T16:19:33.419+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-06T16:19:33.440+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-07-06T09:19:29.407839+00:00 [queued]>
[2024-07-06T16:19:33.446+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-07-06T09:19:29.407839+00:00 [queued]>
[2024-07-06T16:19:33.446+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-06T16:19:33.459+0700] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): download_launches> on 2024-07-06 09:19:29.407839+00:00
[2024-07-06T16:19:33.463+0700] {standard_task_runner.py:63} INFO - Started process 56511 to run task
[2024-07-06T16:19:33.465+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'download_rocket_launches', 'download_launches', 'manual__2024-07-06T09:19:29.407839+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/rocket_dag.py', '--cfg-path', '/tmp/tmp6r8jjydy']
[2024-07-06T16:19:33.466+0700] {standard_task_runner.py:91} INFO - Job 4: Subtask download_launches
[2024-07-06T16:19:33.509+0700] {task_command.py:426} INFO - Running <TaskInstance: download_rocket_launches.download_launches manual__2024-07-06T09:19:29.407839+00:00 [running]> on host acer
[2024-07-06T16:19:33.593+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='download_rocket_launches' AIRFLOW_CTX_TASK_ID='download_launches' AIRFLOW_CTX_EXECUTION_DATE='2024-07-06T09:19:29.407839+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-06T09:19:29.407839+00:00'
[2024-07-06T16:19:33.594+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-06T16:19:33.595+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-06T16:19:33.596+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "curl -o $(pwd)/assets/launces.json -L 'https://ll.thespacedevs.com/2.0.0/launch/upcoming'"]
[2024-07-06T16:19:33.604+0700] {subprocess.py:86} INFO - Output:
[2024-07-06T16:19:33.611+0700] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-07-06T16:19:33.612+0700] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-07-06T16:19:34.752+0700] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[2024-07-06T16:19:35.673+0700] {subprocess.py:93} INFO - Warning: Failed to open the file /tmp/airflowtmp00eop29f/assets/launces.json:
[2024-07-06T16:19:35.674+0700] {subprocess.py:93} INFO - Warning: No such file or directory
[2024-07-06T16:19:35.674+0700] {subprocess.py:93} INFO -  84 23320   84 19762    0     0   9581      0  0:00:02  0:00:02 --:--:--  9581
[2024-07-06T16:19:35.674+0700] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2024-07-06T16:19:35.676+0700] {subprocess.py:97} INFO - Command exited with return code 23
[2024-07-06T16:19:35.676+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-06T16:19:35.685+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/acer/.local/share/virtualenvs/custom_airflow-E5ZHcY_K/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acer/.local/share/virtualenvs/custom_airflow-E5ZHcY_K/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acer/.local/share/virtualenvs/custom_airflow-E5ZHcY_K/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acer/.local/share/virtualenvs/custom_airflow-E5ZHcY_K/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2024-07-06T16:19:35.689+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=download_launches, run_id=manual__2024-07-06T09:19:29.407839+00:00, execution_date=20240706T091929, start_date=20240706T091933, end_date=20240706T091935
[2024-07-06T16:19:35.700+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task download_launches (Bash command failed. The command returned a non-zero exit code 23.; 56511)
[2024-07-06T16:19:35.733+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-06T16:19:35.755+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-06T16:19:35.761+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
